"""Initial migration

Revision ID: 6a5c838603ba
Revises: 7b5f3c1259d9
Create Date: 2025-01-16 15:31:39.881705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5c838603ba'
down_revision = '7b5f3c1259d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projectName', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('projectName')

    # ### end Alembic commands ###
