"""Initial migration

Revision ID: 7b5f3c1259d9
Revises: 5719f318b810
Create Date: 2025-01-16 12:29:50.804657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b5f3c1259d9'
down_revision = '5719f318b810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biddings', schema=None) as batch_op:
        batch_op.alter_column('approvedBy',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_foreign_key(None, 'projects', ['projectId'], ['projectId'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('approvedBy',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
